# Generated by Django 3.2.8 on 2021-11-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
