# Generated by Django 3.2.9 on 2021-11-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
