# Generated by Django 3.2.9 on 2021-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Blog/default.jpg', upload_to='Blog/'),
        ),
    ]
