# Generated by Django 3.2.10 on 2021-12-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='approve',
        ),
    ]
