# Generated by Django 3.2.10 on 2021-12-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_rename_approved_comment_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approve',
            new_name='approved',
        ),
    ]
