# Generated by Django 3.2.10 on 2021-12-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_rename_approve_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',)},
        ),
    ]
