# Generated by Django 3.2.9 on 2021-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsite', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
